import { forwardRef } from 'react'
import type { LucideProps } from 'lucide-react'
import * as Lucide from 'lucide-react'

export type IconComponent = Lucide.LucideIcon

function icon(Glyph: IconComponent): IconComponent {
  return forwardRef<SVGSVGElement, LucideProps>(function AppIcon(
    { size, className, ...props },
    ref,
  ) {
    // Explicit sizes of 24px or more belong to illustrations; UI icons share CSS sizing.
    const uiIcon = size === undefined || (typeof size === 'number' && size < 24)
    const iconClassName = [uiIcon && 'ui-icon', className].filter(Boolean).join(' ')
    return <Glyph ref={ref} size={size ?? 24} className={iconClassName} {...props} />
  }) as IconComponent
}

export const AlertTriangle = icon(Lucide.AlertTriangle)
export const AlignLeft = icon(Lucide.AlignLeft)
export const AlignCenter = icon(Lucide.AlignCenter)
export const AlignRight = icon(Lucide.AlignRight)
export const AlignJustify = icon(Lucide.AlignJustify)
export const Archive = icon(Lucide.Archive)
export const ArchiveRestore = icon(Lucide.ArchiveRestore)
export const ArrowDown = icon(Lucide.ArrowDown)
export const ArrowDownWideNarrow = icon(Lucide.ArrowDownWideNarrow)
export const ArrowLeft = icon(Lucide.ArrowLeft)
export const ArrowRight = icon(Lucide.ArrowRight)
export const ArrowUp = icon(Lucide.ArrowUp)
export const Bold = icon(Lucide.Bold)
export const Book = icon(Lucide.Book)
export const BookOpen = icon(Lucide.BookOpen)
export const BookPlus = icon(Lucide.BookPlus)
export const Briefcase = icon(Lucide.Briefcase)
export const Calendar = icon(Lucide.Calendar)
export const CalendarDays = icon(Lucide.CalendarDays)
export const Camera = icon(Lucide.Camera)
export const Check = icon(Lucide.Check)
export const ChevronDown = icon(Lucide.ChevronDown)
export const ChevronRight = icon(Lucide.ChevronRight)
export const Code = icon(Lucide.Code)
export const Columns2 = icon(Lucide.Columns2)
export const Code2 = icon(Lucide.Code2)
export const Coffee = icon(Lucide.Coffee)
export const Copy = icon(Lucide.Copy)
export const Dumbbell = icon(Lucide.Dumbbell)
export const ExternalLink = icon(Lucide.ExternalLink)
export const Feather = icon(Lucide.Feather)
export const FilePlus2 = icon(Lucide.FilePlus2)
export const FileText = icon(Lucide.FileText)
export const Files = icon(Lucide.Files)
export const Flag = icon(Lucide.Flag)
export const Folder = icon(Lucide.Folder)
export const FolderInput = icon(Lucide.FolderInput)
export const FolderOpen = icon(Lucide.FolderOpen)
export const FolderPlus = icon(Lucide.FolderPlus)
export const Gamepad2 = icon(Lucide.Gamepad2)
export const Globe = icon(Lucide.Globe)
export const GraduationCap = icon(Lucide.GraduationCap)
export const Heart = icon(Lucide.Heart)
export const Highlighter = icon(Lucide.Highlighter)
export const Home = icon(Lucide.Home)
export const ImagePlus = icon(Lucide.ImagePlus)
export const Inbox = icon(Lucide.Inbox)
export const IndentDecrease = icon(Lucide.IndentDecrease)
export const IndentIncrease = icon(Lucide.IndentIncrease)
export const Info = icon(Lucide.Info)
export const Italic = icon(Lucide.Italic)
export const Keyboard = icon(Lucide.Keyboard)
export const Lightbulb = icon(Lucide.Lightbulb)
export const Link = icon(Lucide.Link)
export const Link2 = icon(Lucide.Link2)
export const List = icon(Lucide.List)
export const ListOrdered = icon(Lucide.ListOrdered)
export const ListTodo = icon(Lucide.ListTodo)
export const LoaderCircle = icon(Lucide.LoaderCircle)
export const MapPin = icon(Lucide.MapPin)
export const Maximize2 = icon(Lucide.Maximize2)
export const Menu = icon(Lucide.Menu)
export const Minimize2 = icon(Lucide.Minimize2)
export const Minus = icon(Lucide.Minus)
export const Moon = icon(Lucide.Moon)
export const MoreHorizontal = icon(Lucide.MoreHorizontal)
export const MoreVertical = icon(Lucide.MoreVertical)
export const Music = icon(Lucide.Music)
export const Notebook = icon(Lucide.Notebook)
export const Palette = icon(Lucide.Palette)
export const PanelLeft = icon(Lucide.PanelLeft)
export const PanelLeftClose = icon(Lucide.PanelLeftClose)
export const PanelsTopLeft = icon(Lucide.PanelsTopLeft)
export const PenLine = icon(Lucide.PenLine)
export const Pencil = icon(Lucide.Pencil)
export const Pin = icon(Lucide.Pin)
export const PinOff = icon(Lucide.PinOff)
export const Plane = icon(Lucide.Plane)
export const Plus = icon(Lucide.Plus)
export const Quote = icon(Lucide.Quote)
export const Redo2 = icon(Lucide.Redo2)
export const RefreshCw = icon(Lucide.RefreshCw)
export const RotateCcw = icon(Lucide.RotateCcw)
export const FileSearch = icon(Lucide.FileSearch)
export const Search = icon(Lucide.Search)
export const Settings2 = icon(Lucide.Settings2)
export const ShoppingBag = icon(Lucide.ShoppingBag)
export const SquareCheck = icon(Lucide.SquareCheck)
export const SquarePen = icon(Lucide.SquarePen)
export const Star = icon(Lucide.Star)
export const StarOff = icon(Lucide.StarOff)
export const Strikethrough = icon(Lucide.Strikethrough)
export const Subscript = icon(Lucide.Subscript)
export const Sun = icon(Lucide.Sun)
export const Superscript = icon(Lucide.Superscript)
export const Table2 = icon(Lucide.Table2)
export const Target = icon(Lucide.Target)
export const TextCursorInput = icon(Lucide.TextCursorInput)
export const Trash2 = icon(Lucide.Trash2)
export const Type = icon(Lucide.Type)
export const Underline = icon(Lucide.Underline)
export const Undo2 = icon(Lucide.Undo2)
export const Unlink2 = icon(Lucide.Unlink2)
export const UserRound = icon(Lucide.UserRound)
export const WrapText = icon(Lucide.WrapText)
export const X = icon(Lucide.X)

export const ChevronLeft = icon(Lucide.ChevronLeft)
export const ChevronsLeft = icon(Lucide.ChevronsLeft)
export const ChevronsRight = icon(Lucide.ChevronsRight)
export const Scan = icon(Lucide.Scan)
export const MoveVertical = icon(Lucide.MoveVertical)
export const MoveHorizontal = icon(Lucide.MoveHorizontal)
