import { test, expect } from '@playwright/test'
import { fileURLToPath } from 'node:url'

test('right sidebar lists every occurrence and navigates exact matches', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(String(error)))
  await page.goto('/')
  await page
    .locator('input[type=file][accept="application/pdf,.pdf"]')
    .setInputFiles(fileURLToPath(new URL('./fixtures/text.pdf', import.meta.url)))
  await expect(page.locator('.pdfViewer canvas').first()).toBeVisible()
  await page.keyboard.press('Control+f')
  const input = page.getByRole('textbox', { name: 'Find in PDF', exact: true })
  const panel = page.getByRole('complementary', { name: 'PDF search results' })
  await input.fill('quiet library')
  await expect(panel.locator('.pdf-search-group')).toHaveCount(6)
  await expect(panel.locator('.pdf-search-result')).toHaveCount(168)
  await panel.locator('.pdf-search-group').nth(3).locator('button').nth(9).click()
  await expect(panel.locator('[role=status]')).toHaveText('94 of 168')
  await expect(page.getByLabel('PDF page', { exact: true })).toHaveValue('4')
  await expect(page.locator('.textLayer .highlight.selected')).toHaveText('quiet library')
  await panel.getByRole('button', { name: 'Next PDF match' }).click()
  await expect(panel.locator('[role=status]')).toHaveText('95 of 168')
  await input.press('Shift+Enter')
  await expect(panel.locator('[role=status]')).toHaveText('94 of 168')
  for (const width of [1280, 900, 680]) {
    await page.setViewportSize({ width, height: width === 1280 ? 800 : 650 })
    await expect(panel).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: test.info().outputPath(`search-${width}.png`) })
  }
  await input.fill('not in this document')
  await expect(panel.getByText('No matches found.')).toBeVisible()
  await expect(panel.locator('.pdf-search-result')).toHaveCount(0)
  await input.fill('Stash PDF')
  await expect(panel.locator('.pdf-search-result')).toHaveCount(6)
  await input.press('Escape')
  await page.keyboard.press('Control+f')
  await expect(panel.locator('.pdf-search-result')).toHaveCount(6)
  await expect(page.locator('.textLayer .highlight.selected')).toHaveText('Stash PDF')
  const group = panel.locator('.pdf-search-group').first()
  await group.locator('summary').click()
  await expect(group.locator('button')).toBeHidden()
  await group.locator('summary').click()
  await expect(group.locator('button')).toBeVisible()
  await input.fill('')
  await expect(panel.locator('.pdf-search-result')).toHaveCount(0)
  await input.press('Escape')
  await expect(panel).toBeHidden()
  await expect(page.getByLabel('PDF pages', { exact: true })).toBeFocused()
  expect(errors).toEqual([])
})
